#!/bin/bash

SERVICENAME="$1"
IMAGENAME="$2"

# This script is run inside the container by the script "run" on the host.
ECODE=$(printf "\e")
echo "$ECODE[93m"
#$ECODE[104m"
cat <<'EOF'

      |                                          |
      |                 ,.     ,.                |
      |                {^ \-"-/ ^}               |
      |                "   """   "               |
      |               { <O> _ <O> }              |
      |               ==_ .:Y:. _==              |
      |             .""  `--^--' "".             |
      |            (,~-~."" "" ,~-~.)            |
      |------------(     )----(     )------------|
      |            ^-'-'-^    ^-'-'-^            |
      |__________________________________________|
      |            |"""" /~.^.~\ """"|           |
      |             ,i-i-i(""(  i-i-i.           |
      |            (o o o ))"")( o o o)          |
      |             \(_) /(""(  \ (_)/           |
      |              `--'  \""\  `--'            |
      |                     )"")                 |
      |                    (""/                  |
      |                     `"                   |
      |                                          |
EOF
echo "$ECODE[0m"
cat <<EOF

      Hello world!
      I'm the dService ${IMAGENAME}.
      I'm installed as ${SERVICENAME}.
      My secret word is ${SECRETWORD}.
      
EOF
