#!/bin/bash

#  ad88888ba                                        88                          88888888ba
# d8"     "8b                                       ""                          88      "8b
# Y8,                                                                           88      ,8P
# `Y8aaaaa,     ,adPPYba,  8b,dPPYba,  8b       d8  88   ,adPPYba,   ,adPPYba,  88aaaaaa8P'  88       88  8b,dPPYba,   8b,dPPYba,    ,adPPYba,  8b,dPPYba,
#   `"""""8b,  a8P_____88  88P'   "Y8  `8b     d8'  88  a8"     ""  a8P_____88  88""""88'    88       88  88P'   `"8a  88P'   `"8a  a8P_____88  88P'   "Y8
#         `8b  8PP"""""""  88           `8b   d8'   88  8b          8PP"""""""  88    `8b    88       88  88       88  88       88  8PP"""""""  88
# Y8a     a8P  "8b,   ,aa  88            `8b,d8'    88  "8a,   ,aa  "8b,   ,aa  88     `8b   "8a,   ,a88  88       88  88       88  "8b,   ,aa  88
#  "Y88888P"    `"Ybbd8"'  88              "8"      88   `"Ybbd8"'   `"Ybbd8"'  88      `8b   `"YbbdP'Y8  88       88  88       88   `"Ybbd8"'  88


#------------------------------------------------------------------------------------
# Initialisation of globals.

set -o nounset
MYDIR=$( dirname "$(readlink -f "$0")" )
source "$MYDIR/utils.sh"

#------------------------------------------------------------------------------------
# showhelp - give some info about the service. SERVICENAME and IMAGENAME are provided by variables.sh.

function showhelp {
cat <<EOF >&2

NAME
   ${SERVICENAME}

SYNOPSIS
   ${CODE_S}${SERVICENAME} help${CODE_E}
      This help.

   ${CODE_S}${SERVICENAME} run${CODE_E}
      Say hello to the world.

   ${CODE_S}${SERVICENAME} configure SECRETWORD${CODE_E}
      Set the secret word.

DESCRIPTION
   A simple dRunner example. Built from ${IMAGENAME}.

EOF
}

#------------------------------------------------------------------------------------
# Run a command in the container. If we had any volumes we'd add in "${DOCKEROPTS[@]}".

function dockerrun {
   docker run -i -t \
      -e "SECRETWORD=${SECRETWORD}" \
      --name="${SERVICENAME}-${COMMAND}" \
      "${IMAGENAME}" "$@"
   local RVAL=$?
   docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
   if [ $RVAL -ne 0 ]; then die "${SERVICENAME} ${COMMAND} failed." ; fi
}

#------------------------------------------------------------------------------------
# The main function. We can add any commands we'd like here!

function main {
   if [ "$#" -eq 0 ]; then
      die "servicerunner must have the install argument."
   fi

   COMMAND="${1}"
   case "$COMMAND" in

         #--- hooks
         install_end)
            [ -v SECRETWORD ] || save_environment "SECRETWORD" "not yet set"
            ;;

          #--- standard (required) commands

         help)
            showhelp
            ;;

         enter)
            shift
            dockerrun /bin/bash "$@"
            ;;

         selftest)
            ;;

         #--- custom commands

         run)
            dockerrun helloworld "${SERVICENAME}" "${IMAGENAME}"
            ;;

         configure)
            [ "$#" -eq 2 ] || die "Usage:\n ${SERVICENAME} configure SECRETWORD"
            save_environment "SECRETWORD" "$2"
            echo "Okay, the secret word is ${2}."
            ;;

         #--- unrecognised commands

         *)
            # For the standard hooks we don't implement we're required to produce
            # no output and set exit code 127 (E_NOTIMPL).
            ! isHook ${COMMAND} || exit 127

            dockerrun funpolice
            die "Unrecognised command ${CODE_S}${COMMAND}${CODE_E}"
            ;;
   esac
}

#------------------------------------------------------------------------------------

main "$@"
